In [4]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from collections import Counter

In [7]:
data = pd.read_csv('movie_bd_v5.csv')
data.sample(5)

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year
1332,tt0388482,32000000,85167639,Transporter 2,Jason Statham|Amber Valletta|Kate Nauta|Alessa...,Louis Leterrier,The Best In The Business Is Back In The Game.,Professional driver Frank Martin is living in ...,87,Action|Thriller|Crime,Canal Plus|Twentieth Century Fox Film Corporat...,8/2/2005,6.1,2005
1584,tt0362227,60000000,219417255,The Terminal,Tom Hanks|Catherine Zeta-Jones|Stanley Tucci|C...,Steven Spielberg,Life is waiting.,Viktor Navorski is a man without a country; hi...,128,Comedy|Drama,DreamWorks SKG|Amblin Entertainment|Parkes/Mac...,6/17/2004,7.0,2004
448,tt1135084,32000000,69055695,Takers,Chris Brown|Hayden Christensen|Matt Dillon|Mic...,John Luessenhop,Who's Taking Who?,"A seasoned team of bank robbers, including Gor...",107,Action|Crime|Drama|Thriller,Rainforest Films,8/26/2010,6.1,2010
1598,tt0370263,70000000,171183863,AVP: Alien vs. Predator,Sanaa Lathan|Raoul Bova|Ewen Bremner|Colin Sal...,Paul W.S. Anderson,Whoever wins... We lose,When scientists discover something in the Arct...,101,Adventure|Science Fiction|Action,Impact Pictures|Studio Babelsberg|Twentieth Ce...,8/12/2004,5.5,2004
857,tt0480239,15000000,4627375,Atlas Shrugged Part I,Taylor Schilling|Paul Johansson|Michael O'Keef...,Paul Johansson,Who is John Galt?,"A powerful railroad executive, Dagny Taggart, ...",97,Drama|Thriller|Science Fiction|Mystery,Atlas Productions,4/14/2011,4.8,2011

In [3]:
data.describe()

             budget       revenue      runtime  vote_average  release_year
count  1.889000e+03  1.889000e+03  1889.000000   1889.000000   1889.000000
mean   5.431083e+07  1.553653e+08   109.658549      6.140762   2007.860773
std    4.858721e+07  2.146698e+08    18.017041      0.764763      4.468841
min    5.000000e+06  2.033165e+06    63.000000      3.300000   2000.000000
25%    2.000000e+07  3.456058e+07    97.000000      5.600000   2004.000000
50%    3.800000e+07  8.361541e+07   107.000000      6.100000   2008.000000
75%    7.200000e+07  1.782626e+08   120.000000      6.600000   2012.000000
max    3.800000e+08  2.781506e+09   214.000000      8.100000   2015.000000

# Предобработка

In [15]:
answers = {} # создадим словарь для ответов

# тут другие ваши предобработки колонок например:

#the time given in the dataset is in string format.
#So we need to change this in datetime format
# ...

# 1. У какого фильма из списка самый большой бюджет?

Использовать варианты ответов в коде решения запрещено.    
Вы думаете и в жизни у вас будут варианты ответов?)

In [157]:
# в словарь вставляем номер вопроса и ваш ответ на него
# Пример: 
answers['1'] = '2. Spider-Man 3 (tt0413300)'
# запишите свой вариант ответа
answers['1'] = 'Pirates of the Caribbean: On Stranger Tides (tt1298650)'
# если ответили верно, можете добавить комментарий со значком "+"

In [7]:
# тут пишем ваш код для решения данного вопроса:
df = data[data.budget == data.budget.max()]

ВАРИАНТ 2

In [193]:
# можно добавлять разные варианты решения
df = data.sort_values(by = 'budget', ascending = False)

# 2. Какой из фильмов самый длительный (в минутах)?

In [158]:
# думаю логику работы с этим словарем вы уже поняли, 
# по этому не буду больше его дублировать
answers['2'] = 'Gods and Generals (tt0279111)'

In [9]:
df = data[data.runtime == data.runtime.max()]

# 3. Какой из фильмов самый короткий (в минутах)?

In [159]:
answers['3'] = 'Winnie the Pooh (tt1449283)'

In [11]:
df = data[data.runtime == data.runtime.min()]

# 4. Какова средняя длительность фильмов?

In [160]:
answers['4'] = 110

In [39]:
df = round(data.runtime.mean())

# 5. Каково медианное значение длительности фильмов?

In [161]:
answers['5'] = 107

In [ ]:
df = data.runtime.median()

# 6. Какой самый прибыльный фильм?
#### Внимание! Здесь и далее под «прибылью» или «убытками» понимается разность между сборами и бюджетом фильма. (прибыль = сборы - бюджет) в нашем датасете это будет (profit = revenue - budget)

In [162]:
# лучше код получения столбца profit вынести в Предобработку что в начале
answers['6'] = 'Avatar (tt0499549)'

In [43]:
data['profit'] = data['revenue'] - data['budget']
data.sort_values(by='profit', ascending = False).head(1)

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit
239,tt0499549,237000000,2781505847,Avatar,Sam Worthington|Zoe Saldana|Sigourney Weaver|S...,James Cameron,Enter the World of Pandora.,"In the 22nd century, a paraplegic Marine is di...",162,Action|Adventure|Fantasy|Science Fiction,Ingenious Film Partners|Twentieth Century Fox ...,12/10/2009,7.1,2009,2544505847

# 7. Какой фильм самый убыточный?

In [163]:
answers['7'] = 'The Lone Ranger (tt1210819)'

In [44]:
data.sort_values(by='profit', ascending = True).head(1)

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit
1245,tt1210819,255000000,89289910,The Lone Ranger,Johnny Depp|Armie Hammer|William Fichtner|Hele...,Gore Verbinski,Never Take Off the Mask,The Texas Rangers chase down a gang of outlaws...,149,Action|Adventure|Western,Walt Disney Pictures|Jerry Bruckheimer Films|I...,7/3/2013,6.0,2013,-165710090

# 8. У скольких фильмов из датасета объем сборов оказался выше бюджета?

In [164]:
answers['8'] = 1478

In [51]:
df = data[data.revenue > data.budget].imdb_id.count()
display(df)

1478

# 9. Какой фильм оказался самым кассовым в 2008 году?

In [165]:
answers['9'] = 'The Dark Knight (tt0468569)'

In [78]:
df = data[(data.release_year == 2008)]
df = df[df.revenue.max() == df.revenue]

# 10. Самый убыточный фильм за период с 2012 по 2014 г. (включительно)?

In [166]:
answers['10'] = 'The Lone Ranger (tt1210819)'

In [90]:
df = data[(data.release_year <= 2014) & (data.release_year >= 2012)]
df = data[data.profit == data.profit.min()]
display(df)

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit
1245,tt1210819,255000000,89289910,The Lone Ranger,Johnny Depp|Armie Hammer|William Fichtner|Hele...,Gore Verbinski,Never Take Off the Mask,The Texas Rangers chase down a gang of outlaws...,149,Action|Adventure|Western,Walt Disney Pictures|Jerry Bruckheimer Films|I...,7/3/2013,6.0,2013,-165710090

# 11. Какого жанра фильмов больше всего?

In [167]:
# эту задачу тоже можно решать разными подходами, попробуй реализовать разные варианты
# если будешь добавлять функцию - выноси ее в предобработку что в начале\
answers['11'] = 'Drama'

In [92]:
sum_geners = pd.Series(data['genres'].str.cat(sep ='|').split('|')) 
display(s.value_counts())

Drama              782
Comedy             683
Thriller           596
Action             582
Adventure          415
Crime              315
Romance            308
Family             260
Science Fiction    248
Fantasy            222
Horror             176
Mystery            168
Animation          139
Music               64
History             62
War                 58
Western             19
Documentary          8
Foreign              2
dtype: int64

ВАРИАНТ 2

# 12. Фильмы какого жанра чаще всего становятся прибыльными?

In [168]:
answers['12'] = 'Drama'

In [93]:
df = data[(data.profit > 0)]
s = pd.Series(df['genres'].str.cat(sep ='|').split('|')) 
display(s.value_counts())

Drama              560
Comedy             551
Thriller           446
Action             444
Adventure          337
Romance            242
Crime              231
Family             226
Science Fiction    195
Fantasy            188
Horror             150
Animation          120
Mystery            119
Music               47
History             46
War                 41
Western             12
Documentary          7
dtype: int64

# 13. У какого режиссера самые большие суммарные кассовые сбооры?

In [169]:
answers['13'] = 'Peter Jackson'

In [94]:
directors = pd.Series(data['director'].str.cat(sep ='|').split('|')) 
directors = directors.value_counts()
for i in directors.index:
    for a in data.index:
        if i in data.director[a]:
            directors[i] = directors[i] + data.revenue[a]
display(directors.sort_values(ascending = False))

Peter Jackson        6490593693
Christopher Nolan    4167548510
David Yates          4154295629
Michael Bay          3886938968
J.J. Abrams          3579169921
                        ...
David MichÃ´d           2295424
Steven Shainberg        2281090
Paul Schrader           2062067
Keanu Reeves            2054942
Simon Hunter            2033166
Length: 997, dtype: int64

# 14. Какой режисер снял больше всего фильмов в стиле Action?

In [170]:
answers['14'] = 'Robert Rodriguez'

In [95]:
directors = pd.Series(data['director'].str.cat(sep ='|').split('|')) 
directors = directors.value_counts()
for i in directors.index:
    for a in data.index:
        if i in data.director[a]:
            if 'Action' in data.genres[a]:
                directors[i] = directors[i] + 1
display(directors.sort_values(ascending = False))

Robert Rodriguez      20
Ridley Scott          18
Clint Eastwood        15
Michael Bay           15
Paul W.S. Anderson    14
                      ..
Bonnie Hunt            1
Robert B. Weide        1
Olatunde Osunsanmi     1
Roberts Gannaway       1
Sam Taylor-Johnson     1
Length: 997, dtype: int64

# 15. Фильмы с каким актером принесли самые высокие кассовые сборы в 2012 году?

In [171]:
answers['15'] = 'Chris Hemsworth'

In [ ]:
df = data[data.release_year == 2012]
df_cast = pd.Series(df['cast'].str.cat(sep='|').split('|'))
df_cast = df_cast.value_counts()
for i in df_cast.index:
    df_cast[i] = df['revenue'][df['cast'].map(lambda x: True if i in x else False)].sum()
display(df_cast.sort_values(ascending = False))

# 16. Какой актер снялся в большем количестве высокобюджетных фильмов?

In [172]:
answers['16'] = 'Matt Damon'

In [97]:
df = data[(data['budget'] > data['budget'].mean())]
df_cast = pd.Series(df['cast'].str.cat(sep='|').split('|'))
df_cast = df_cast.value_counts()
display(df_cast.sort_values(ascending = False))

Matt Damon           18
Adam Sandler         17
Angelina Jolie       16
Samuel L. Jackson    15
Tom Cruise           15
                     ..
Ryan Gosling          1
Philip Winchester     1
Archie Panjabi        1
Julia Ormond          1
Ossie Davis           1
Length: 1505, dtype: int64

# 17. В фильмах какого жанра больше всего снимался Nicolas Cage?

In [173]:
answers['17'] = 'Action'

In [ ]:
df_NC = data[data.cast.str.contains('Nicolas Cage')]
df_NC = pd.Series(df_NC['genres'].str.cat(sep ='|').split('|')) 
df_NC = df_NC.value_counts()
display(df_NC.sort_values(ascending = False))

# 18. Самый убыточный фильм от Paramount Pictures

In [174]:
answers['18'] = 'K-19: The Widowmaker (tt0267626)'

In [ ]:
df_paramount = data[data.production_companies.str.contains('Paramount Pictures')]
display(df_paramount.sort_values('profit', ascending = True).head(1))

# 19. Какой год стал самым успешным по суммарным кассовым сборам?

In [175]:
answers['19'] = 2015

In [100]:
release_df = data.release_year.value_counts()
for i in release_df.index:
    release_df[i] = data['revenue'][data['release_year'].map(lambda x: True if i == x else False)].sum()
display(release_df.sort_values(ascending = False).head(1))

2015    25449202382
Name: release_year, dtype: int64

# 20. Какой самый прибыльный год для студии Warner Bros?

In [176]:
answers['20'] = 2014

In [ ]:
df_Warner = data[data.production_companies.str.contains('Warner Bros')]
release_df = df_Warner.release_year.value_counts()
for i in release_df.index:
    release_df[i] = df_Warner['profit'][df_Warner['release_year'].map(lambda x: True if i == x else False)].sum()
display(release_df.sort_values(ascending = False).head(1))

# 21. В каком месяце за все годы суммарно вышло больше всего фильмов?

In [177]:
answers['21'] = 'Сентябрь'

In [101]:
import re
s = []
release_df = data.release_date.value_counts()
for i in range(1, 13):
    pattern = str(i) +'/'
    count_df = data[data.release_date.str.match(pattern, na=False)]
    s.append(len(count_df.index))
df_my = pd.DataFrame([s], columns = ['Jan', 'Feb', 'Mar', 'Apr.', 'May', 'June', 'July', 'Aug', 'Sep', 'Oct.', 'Nov.', 'Dec.'])
m = df_my.max()
display(m.sort_values(ascending = False))

Sep     227
Dec.    190
Oct.    186
Aug     161
Mar     156
Apr.    149
June    147
Nov.    146
July    142
May     140
Feb     135
Jan     110
dtype: int64

# 22. Сколько суммарно вышло фильмов летом? (за июнь, июль, август)

In [178]:
answers['22'] = 450

In [105]:
sum_films = m['June'] + m['July'] + m['Aug']
display(sum_films)

450

# 23. Для какого режиссера зима – самое продуктивное время года?

In [179]:
answers['23'] = 'Peter Jackson'

In [106]:
df_winter = data[data.release_date.str.match('12/' or '1/' or '6/', na=False)]
df_director = pd.Series(df_winter['director'].str.cat(sep ='|').split('|'))
df_director = df_director.value_counts()
display(df_director)

Peter Jackson        7
Clint Eastwood       5
Nancy Meyers         4
Steven Soderbergh    4
Martin Scorsese      3
                    ..
Sam Mendes           1
Carl Rinsch          1
Robert Zemeckis      1
J.J. Abrams          1
Bill Condon          1
Length: 153, dtype: int64

# 24. Какая студия дает самые длинные названия своим фильмам по количеству символов?

In [180]:
answers['24'] = 'Four By Two Productions'

In [107]:
data = pd.read_csv('C:/Users/Klikan/SkillFactory/Unit_1/test/movie_bd_v5.csv')
df_compains = pd.Series(data['production_companies'].str.cat(sep='|').split('|'))
df_compains = df_compains.value_counts()
data['len'] = data['original_title'].str.len()
for i in df_compains.index:
    df_compains[i] = data['len'][data['production_companies'].map(lambda x: True if i in x else False)].mean()
display(df_compains.sort_values(ascending = False))

Four By Two Productions       83
Jim Henson Company, The       59
Dos Corazones                 47
Polsky Films                  46
Museum Canada Productions     46
                              ..
Everest Entertainment          3
Berlanti Productions           3
Global Entertainment Group     2
XM2 Productions                2
Ixtlan Productions             2
Length: 1771, dtype: int64

# 25. Описание фильмов какой студии в среднем самые длинные по количеству слов?

In [181]:
answers['25'] = 'Midnight Picture Show'

In [108]:
data['len'] = data['overview'].str.len()
for i in df_compains.index:
    df_compains[i] = data['len'][data['production_companies'].map(lambda x: True if i in x else False)].mean()
display(df_compains.sort_values(ascending = False))

Midnight Picture Show                    1000
Room 9 Entertainment                      964
Brookwell-McNamara Entertainment          936
Crest Animation Productions               909
Lions Gate Family Entertainment           909
                                         ...
Projection Pictures                        74
Henceforth                                 74
Phantom Four                               72
Empire Pictures                            62
Motion Picture Corporation of America      59
Length: 1771, dtype: int64

# 26. Какие фильмы входят в 1 процент лучших по рейтингу? 
по vote_average

In [182]:
answers['26'] = 'Inside Out, The Dark Knight, 12 Years a Slave'

In [110]:
df_percent = data[['vote_average', 'original_title']].sort_values(by = 'vote_average', ascending = False)
display(df_percent[:(round(len(df_percent)*0.01))])

      vote_average                                 original_title
599            8.1                                The Dark Knight
118            8.0                                   Interstellar
125            8.0                             The Imitation Game
9              8.0                                     Inside Out
34             8.0                                           Room
1183           7.9                        The Wolf of Wall Street
128            7.9                                      Gone Girl
1191           7.9                               12 Years a Slave
119            7.9                        Guardians of the Galaxy
1081           7.9  The Lord of the Rings: The Return of the King
1800           7.9                                        Memento
370            7.9                                      Inception
872            7.9                                    The Pianist
138            7.9                       The Grand Budapest Hotel
1188           7.8                                            Her
28             7.8                                      Spotlight
124            7.8                                     Big Hero 6
177            7.8                         The Fault in Our Stars
863            7.8          The Lord of the Rings: The Two Towers

# 27. Какие актеры чаще всего снимаются в одном фильме вместе?

In [183]:
answers['27'] = 'Daniel Radcliffe & Rupert Grint'

In [117]:
import itertools as it
c = Counter()
for actors in data['cast']:
    artists = actors.split('|')
    for j in list(it.combinations(artists, 2)):
        if j not in c:
            c[j] = 1
        else:
            c[j] +=1
c.most_common(3)

[(('Daniel Radcliffe', 'Rupert Grint'), 8),
 (('Daniel Radcliffe', 'Emma Watson'), 8),
 (('Rupert Grint', 'Emma Watson'), 7)]

ВАРИАНТ 2

# Submission

In [184]:
# в конце можно посмотреть свои ответы к каждому вопросу
display(answers)

{'1': 'Pirates of the Caribbean: On Stranger Tides (tt1298650)',
 '2': 'Gods and Generals (tt0279111)',
 '3': 'Winnie the Pooh (tt1449283)',
 '4': 110,
 '9': 'The Dark Knight (tt0468569)',
 '8': 1478,
 '11': 'Drama',
 '14': 'Robert Rodriguez',
 '19': 2015,
 '18': 'K-19: The Widowmaker (tt0267626)',
 '21': 'Сентябрь',
 '27': 'Daniel Radcliffe & Rupert Grint',
 '5': 107,
 '6': 'Avatar (tt0499549)',
 '7': 'The Lone Ranger (tt1210819)',
 '10': 'The Lone Ranger (tt1210819)',
 '12': 'Drama',
 '13': 'Peter Jackson',
 '15': 'Chris Hemsworth',
 '16': 'Matt Damon',
 '17': 'Action',
 '20': 2014,
 '22': 450,
 '23': 'Peter Jackson',
 '24': 'Four By Two Productions',
 '25': 'Midnight Picture Show',
 '26': 'Inside Out, The Dark Knight, 12 Years a Slave'}

In [156]:
# и убедиться что ни чего не пропустил)
len(answers)

27